export const SET_LOADING = 'SET_LOADING';
export const SETLOADING = 'SET_LOADING';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SET_BANK_ACCOUNT = 'SET_BANK_ACCOUNT';
export const SET_ALL_TRANSACTIONS = 'SET_ALL_TRANSACTIONS';
